[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ZiYue4D"
authors = [{name = "ZiYueCommentary", email = "ziyuecommentary@gmail.com"}]
dynamic = ["version", "description"]
